[package]
name = "needletail"
version = "0.1.0"
authors = ["Roderick Bovee <roderick@onecodex.com>"]

[dependencies]
memchr = "0.1.11"

[dev-dependencies]
bencher = "0.1.1"

[[bench]]
name = "benchmark"
harness = false
