[package]
name = "needletail"
version = "0.1.0"
authors = ["Roderick Bovee <roderick@onecodex.com>"]


[dependencies]
nom = { version = "~1.2.3", git = "https://github.com/bovee/nom" }
memchr = "0.1.11"
